### ISSUE TITLE
[Back End] Found vulnerabilities in dev_backend

### ISSUE THREAD

**Issue by p-amonpitakpun** [2110423-2019-2/sec33_Matcher#30]
(branch: hotfix_backend_0.0.1)
Found the vulnerabilities after using `npm install` from dev_backend branch.
>npm WARN fastphoto-backend@1.0.0 No repository field.
npm WARN The package ts-node is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
removed 8 packages, updated 2 packages and audited 1077 packages in 7.167s
found 6 vulnerabilities (5 low, 1 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details

There is still some vulnerabilities left after using `npm audit fix`.
>npm WARN fastphoto-backend@1.0.0 No repository field.
npm WARN The package ts-node is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
removed 8 packages and updated 2 packages in 1.818s
fixed 3 of 6 vulnerabilities in 1077 scanned packages
  3 vulnerabilities required manual review and could not be updated

**Comment by nisaruj** [comment]
The `minimist` package which has unfixed vulnerabilities are used in development environment (eslint and mocha). I think it would be fine if we ignore this.
