### ISSUE TITLE
dev_backend: Postman is blocked by  CORS

### ISSUE THREAD

**Issue by p-amonpitakpun** [2110423-2019-2/sec33_Matcher#60]
สามารถทำให้หากใช้  `npm run dev` จะไม่ติด CORS ได้หรือเปล่าเพื่อใช้ทดสอบ Postman

**Comment by nisaruj** [comment]
in progress

**Comment by nisaruj** [comment]
https://github.com/2110423-2019-2/sec33_Matcher/commit/86a940111b7a44c95811ce2ad5896e9833bfffbb You can now add `DISABLE_CORS=1` in .env file to disable cors.
